name: Deployment Workflow
on:
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
    - name: running ssh commands on DO server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.TACGIGAU_PRIVATE_KEY }}
        port: 22
        script: |
          cd arbit
          _build/prod/rel/arbit/bin/arbit stop
          git pull
          chmod a+x ./build.sh
          ./build.sh
          # mix deps.get --only prod
          # MIX_ENV=prod mix compile
          # npm run deploy --prefix ./assets
          # mix phx.digest
          # MIX_ENV=prod mix ecto.migrate
          # MIX_ENV=prod mix release --overwrite
          _build/prod/rel/arbit/bin/arbit daemon
