name: Deployment Workflow
on:
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
    - name: testing DO server ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.TACGIGAU_PRIVATE_KEY }}
        port: 22
        script: whoami
